# Generated by Django 3.2.19 on 2023-05-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
    ]
