# Generated by Django 3.2.19 on 2023-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
