# Generated by Django 3.2.19 on 2023-05-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_new_stratum'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='pc_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
