# Generated by Django 3.2.19 on 2023-05-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_new_pc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
