# Generated by Django 3.2.19 on 2023-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_new_pc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tdelay',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='toffset',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
    ]
