# Generated by Django 3.2.19 on 2023-06-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20230525_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='t0',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=250, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='t1',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=250, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='t2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=250, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='t3',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=250, null=True),
        ),
    ]
