# Generated by Django 3.2.19 on 2023-06-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_new_pc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pc_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
