# Generated by Django 3.2.19 on 2023-06-08 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_new_pc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pc_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 6, 8, 10, 24, 41, 525672, tzinfo=utc), null=True),
        ),
    ]
