# Generated by Django 3.2.19 on 2023-06-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_new_pc_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
