# Generated by Django 3.2.19 on 2023-06-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20230609_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='Img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
