# Generated by Django 3.2.19 on 2023-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='n',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
