# Generated by Django 3.2.19 on 2023-06-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20230620_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
