# Generated by Django 3.2.19 on 2023-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='iserror',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
