# Generated by Django 3.2.19 on 2023-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_new_iserror'),
    ]

    operations = [
        migrations.AddField(
            model_name='n',
            name='errmsg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='n',
            name='iserror',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
